"""corrected class note

Revision ID: 0fe0f891a5ff
Revises: 250b355692dc
Create Date: 2023-04-01 09:32:32.969443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe0f891a5ff'
down_revision = '250b355692dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('note', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'role_id')
    op.drop_column('note', 'is_active')
    # ### end Alembic commands ###
