"""Init last db5

Revision ID: 1140aa684f64
Revises: 4683e37e04ec
Create Date: 2023-04-10 21:51:23.954646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1140aa684f64'
down_revision = '4683e37e04ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
