"""corrected note

Revision ID: 250b355692dc
Revises: 855aba0f9ad3
Create Date: 2023-04-01 08:30:24.944682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b355692dc'
down_revision = '855aba0f9ad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
