"""Init last db

Revision ID: 2f4470c25cf2
Revises: 8686a9589b56
Create Date: 2023-04-10 21:09:24.140887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4470c25cf2'
down_revision = '8686a9589b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
