"""corrected models/user1

Revision ID: 3eb4e4c1f168
Revises: 677031f8b672
Create Date: 2023-04-15 09:24:13.460848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb4e4c1f168'
down_revision = '677031f8b672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
