"""Init last db4

Revision ID: 4683e37e04ec
Revises: 77c02a240ecc
Create Date: 2023-04-10 21:49:34.384715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4683e37e04ec'
down_revision = '77c02a240ecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
