"""4 corrected

Revision ID: 46b53ef849f1
Revises: 6acc2b8276d2
Create Date: 2023-04-03 17:28:42.633597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b53ef849f1'
down_revision = '6acc2b8276d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
