"""finally correct

Revision ID: 5b40468a48eb
Revises: 6a8d750fac3c
Create Date: 2023-04-01 10:24:09.828942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b40468a48eb'
down_revision = '6a8d750fac3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
