"""corrected models/user

Revision ID: 677031f8b672
Revises: 1053b59e3008
Create Date: 2023-04-15 09:15:08.358709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677031f8b672'
down_revision = '1053b59e3008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
