"""third corrected

Revision ID: 6acc2b8276d2
Revises: 5b40468a48eb
Create Date: 2023-04-03 17:22:30.325626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acc2b8276d2'
down_revision = '5b40468a48eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('note_owner_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    op.drop_column('note', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_owner_id_fkey', 'note', 'user', ['owner_id'], ['id'])
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
