"""final create

Revision ID: 704324ed9b85
Revises: 1140aa684f64
Create Date: 2023-04-11 18:00:53.657670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704324ed9b85'
down_revision = '1140aa684f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
