"""last corrected

Revision ID: 723536b80af0
Revises: 8dfeb49f788c
Create Date: 2023-04-05 17:48:38.997206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723536b80af0'
down_revision = '8dfeb49f788c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
