"""Init last db3

Revision ID: 77c02a240ecc
Revises: f80ae29537ab
Create Date: 2023-04-10 21:22:27.833398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c02a240ecc'
down_revision = 'f80ae29537ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
