"""corrected once more

Revision ID: 855aba0f9ad3
Revises: b158918034b1
Create Date: 2023-04-01 08:21:43.001512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855aba0f9ad3'
down_revision = 'b158918034b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
