"""6  corrected

Revision ID: 8dfeb49f788c
Revises: ca7ae2fdf411
Create Date: 2023-04-03 18:16:44.709752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfeb49f788c'
down_revision = 'ca7ae2fdf411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
