"""corrected moduls

Revision ID: b158918034b1
Revises: b584c4c606c3
Create Date: 2023-04-01 08:14:57.949871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b158918034b1'
down_revision = 'b584c4c606c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
