"""corrected class note1

Revision ID: b514d3ae0c35
Revises: 0fe0f891a5ff
Create Date: 2023-04-01 09:38:33.437595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b514d3ae0c35'
down_revision = '0fe0f891a5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
