"""update db

Revision ID: b584c4c606c3
Revises: 56c89ef083db
Create Date: 2023-03-27 18:22:48.554728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b584c4c606c3'
down_revision = '56c89ef083db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
