"""corrected models finaly

Revision ID: b973689ec664
Revises: 325f5bc8106d
Create Date: 2023-04-15 09:33:08.799652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b973689ec664'
down_revision = '325f5bc8106d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
