"""5 corrected

Revision ID: ca7ae2fdf411
Revises: 46b53ef849f1
Create Date: 2023-04-03 18:10:09.685220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7ae2fdf411'
down_revision = '46b53ef849f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
