"""Init last db1

Revision ID: f80ae29537ab
Revises: 2f4470c25cf2
Create Date: 2023-04-10 21:14:51.609311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80ae29537ab'
down_revision = '2f4470c25cf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
